### ISSUE TITLE
Center and padding should be optional

### ISSUE THREAD

**Issue by vvsevolodovich** [ilikerobots/storyboard#11]
The storyboard renders the items with the 8.0 padding and centered. This may not be required for some cases. Let those parameters be optional or adjustable. 

My particular point is that I am overlaying the component with the picture of the same component from Figma. The centrification and paddings do not allow to properly align one against the other.

```
Widget _widgetListItem(Widget w) =>
      Row(mainAxisAlignment: MainAxisAlignment.center, children: [
        Container(padding: const EdgeInsets.symmetric(vertical: 8.0), child: w)
      ]);
```

I can make a pull request for this one if you would.

**Comment by ilikerobots** [comment]
I'd love a PR if you don't mind.  Thanks!

**Comment by vvsevolodovich** [comment]
I submitted a PR https://github.com/ilikerobots/storyboard/pull/13

**Comment by ilikerobots** [comment]
@vlivanov , PR #12 by @cmaster11 seems to accomplish the same and looks simpler and more flexible.  Any objections to using that PR instead?

And so sorry I didn't notice it before! :(

**Comment by vvsevolodovich** [comment]
No objections, @ilikerobots! Let's merge it and issue a new version.
